apiVersion: v1
kind: Secret
metadata:
  name: {{conf_secret_name}}
  namespace: "{{namespace}}"
type: Opaque
stringData:
  db_conn_str: "mongodb://{{dbuser}}:{{dbpass}}@{{dbhost}}:27017/{{dbname}}"
  db_name: {{dbname}}
