# Application objects
- name: Create CoreApiTest Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/service.yml') }}"

- name: Create CoreApiTest Route
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/route.yml') }}"

- name: Handle latest route for LAB deployments
  block:
    - name: Delete latest CoreApiTest Route
      k8s:
        state: absent
        definition: "{{ lookup('template', 'templates/route-latest.yml') }}"

    - name: Create Latest CoreApiTest Route
      k8s:
        state: present
        definition: "{{ lookup('template', 'templates/route-latest.yml') }}"
  when:
    - profile == "dev"
    - newest_deployment.metadata.name != route_destination_service

- name: Create CoreApiTest Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/deployment.yml') }}"
