- name: Find the deployment for deletion
  set_fact:
    deployment_name_for_deletion: "{{item}}"
  loop: "{{coreapitest_deployments.resources}}"
  when:
  - item.metadata.creationTimestamp == timestamp_sorted_list[0]

- name: Print CoreApiTest name for deletion
  debug:
    msg: "{{deployment_name_for_deletion.metadata.name}}"

- name: Remove GovilDeployment
  k8s:
    state: absent
    api_version: gov.il/v1alpha1
    kind: CoreApiTest
    namespace: "{{namespace}}"
    name: "{{deployment_name_for_deletion.metadata.name}}"
