- name: Define timestamps list
  set_fact:
    timestamp_list: []

- name: Construct GovIL Deployment timestamp list
  set_fact:
    timestamp_list: "{{ timestamp_list }} + [ '{{item.metadata.creationTimestamp}}' ]"
  loop: "{{coreapitest_deployments.resources}}"

- name: Sort timestamps list
  set_fact:
    timestamp_sorted_list: "{{timestamp_list | sort }}"

- name: Print sorted deployment list
  debug:
    msg: "{{item}}"
  loop: "{{timestamp_sorted_list}}"

- name: Find the deployment for deletion
  set_fact:
    deployment_name_for_deletion: "{{item}}"
  loop: "{{coreapitest_deployments.resources}}"
  when:
  - item.metadata.creationTimestamp == "{{timestamp_sorted_list[0]}}"

- debug:
    msg: "{{deployment_name_for_deletion.metadata.name}}"

- name: Remove GovilDeployment
  k8s:
    state: absent
    api_version: gov.il/v1alpha1
    kind: CoreApiTest
    namespace: "{{namespace}}"
    name: "{{deployment_name_for_deletion.metadata.name}}"
