# Application objects
- name: Create ReactSample Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/app/service.yml') }}"

- name: Create ReactSample Route
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/app/route.yml') }}"
  when: reactsample_deployment.resources | length == 1

- name: Create ReactSample Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/app/deployment.yml') }}"
