- name: Construct ReactSample timestamp list
  set_fact:
    timestamp_list: "{{ timestamp_list }} + [ '{{item.metadata.creationTimestamp}}' ]"
  loop: "{{reactsample_deployment.resources}}"

- name: Sort timestamps list
  set_fact:
    timestamp_sorted_list: "{{timestamp_list | sort }}"

- name: Find the oldest ReactSample
  set_fact:
    oldest_reactsample: "{{item}}"
  loop: "{{reactsample_deployment.resources}}"
  when:
  - item.metadata.creationTimestamp == timestamp_sorted_list[0]

- name: Remove oldest ReactSample instace
  k8s:
    state: absent
    kind: ReactSample
    api_version: gov.il/v1alpha1
    namespace: "{{namespace}}"
    name: "{{oldest_reactsample.metadata.name}}"
