- name: Search for all ReactSample deployments
  k8s_facts:
    kind: ReactSample
    api_version: gov.il/v1alpha1
    namespace: "{{namespace}}"
    label_selectors:
      - profile = {{profile}}
  register: reactsample_deployment
