apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{latest_route_name}}"
  namespace: "{{namespace}}"
spec:
  host: "{{latest_route_host}}"
  to:
    kind: Service
    name: "{{newest_deployment.metadata.name}}"
