apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
  name: "{{resources.mongo.dbhost}}"
  namespace: "{{namespace}}"
spec:
  replicas: 1
  selector:
    name: "{{resources.mongo.dbhost}}"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: "{{resources.mongo.dbhost}}"
    spec:
      containers:
      - capabilities: {}
        env:
        - name: MONGODB_USER
          value: "{{resources.mongo.dbuser}}"
        - name: MONGODB_PASSWORD
          value: "{{resources.mongo.dbpass}}"
        - name: MONGODB_ADMIN_PASSWORD
          value: "{{resources.mongo.dbpass}}"
        - name: MONGODB_DATABASE
          value: "{{resources.mongo.dbname}}"
        image: "{{resources.mongo.dbimage}}"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 27017
          timeoutSeconds: 1
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
              --eval="quit()"
          initialDelaySeconds: 3
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
