# Create application objects
- name: Waiting for RabbitMQ to be ready
  k8s_facts:
    kind: Deployment
    api_version: apps/v1
    namespace: "{{namespace}}"
    label_selectors:
      - depOwner = {{dep_owner}}
      - profile = {{profile}}
  register: rabbitmq_dep
  until:
    - '"readyReplicas" in rabbitmq_dep.resources[0].status'
    - rabbitmq_dep.resources[0].status.readyReplicas == 1

- name: Geting shared ConfigMap
  k8s_facts:
    kind: ConfigMap
    api_version: v1
    namespace: "{{namespace}}"
    label_selectors:
      - depOwner = {{dep_owner}}
      - profile = {{profile}}
  register: shared_cm

- name: Print Shared ConfigMap dep object
  debug:
    msg: "{{rabbitmq_dep.resources[0].metadata.name}}"

- name: Create POC1 Producer Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/app/deployment.yml') }}"
