apiVersion: gov.il/v1alpha1
kind: Poc12Dep
metadata:
  name: poc12-rabbitmq-dev
  namespace: govil
spec:
  depOwner: poc12
  image: docker.io/rabbitmq:3-management
  namespace: govil
  profile: dev
  queueName: sites
  routeHostSuffix: router.default.svc.cluster.local
  service: poc12-rabbitmq-dev
