# CoreApiTestDep EXAMPLE for CoreApiTest app in LAB environment
apiVersion: gov.il/v1alpha1
kind: CoreApiTestDep
metadata:
  name: coreapitestdep-lab
  labels:
    profile: lab
spec:
  confSecretName: coreapitest-lab
  profile: lab
  namespace: govil
  dbhost: mongo-coreapitest-lab
  dbuser: app
  dbpass: app
  dbname: coreapitestdb
  dbimage: "docker-registry.default.svc:5000/openshift/mongodb:3.6"
