apiVersion: gov.il/v1alpha1
kind: CoreApiTest
metadata:
  labels:
    profile: dev
  name: govil-coreapitest-51ae184
  namespace: govil
spec:
  size: "1"
  appName: govil-coreapitest-51ae184
  confSecretName: govil-coreapitest-51ae184
  containerPort: "8080"
  image: docker.io/dimssss/coreapitest:51ae184-27
  latestRouteHost: coreapitest-dev-latest.router.default.svc.cluster.local
  latestRouteName: coreapitest-latest-dev
  namespace: govil
  profile: dev
  resources:
    mongo:
      dbhost: mongo-govil-coreapitest-51ae184
      dbimage: docker-registry.default.svc:5000/openshift/mongodb:3.6
      dbname: coreapitestdb
      dbpass: app
      dbuser: app
---
apiVersion: gov.il/v1alpha1
kind: CoreApiTest
metadata:
  labels:
    profile: lab
  name: govil-coreapitest-v0-5
  namespace: govil
spec:
  size: "1"
  appName: govil-coreapitest-v0-5
  confSecretName: coreapitest-lab
  containerPort: "8080"
  image: docker.io/dimssss/coreapitest:v0.5
  latestRouteHost: coreapitest-lab.router.default.svc.cluster.local
  latestRouteName: coreapitest-lab
  namespace: govil
  profile: lab
