apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: coreapitestdeps.gov.il
spec:
  group: gov.il
  names:
    kind: CoreApiTestDep
    listKind: CoreApiTestDepList
    plural: coreapitestdeps
    singular: coreapitestdep
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
