apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reactsamples.gov.il
spec:
  group: gov.il
  names:
    kind: ReactSample
    listKind: ReactSampleList
    plural: reactsamples
    singular: reactsample
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
