apiVersion: gov.il/v1alpha1
kind: CoreApiTest
metadata:
  name: govil-coreapitest-9ca9818
spec:
  size: 1
  appName: govil-coreapitest-9ca9818
  image: "docker.io/dimssss/coreapitest:9ca9818-1"
  containerPort: 8080
  profile: dev
  namespace: govil
  resources:
    mongo:
      dbhost: mongo-govil-coreapitest-9ca9818
      dbuser: app
      dbpass: app
      dbname: coreapitestdb
      dbimage: "docker-registry.default.svc:5000/openshift/mongodb:3.6"
  deploymentStrategy:
    type: gb
    weight: 50
