apiVersion: gov.il/v1alpha1
kind: Poc2Consumer
metadata:
  labels:
    profile: dev
  name: govil-poc2-consumer-d3fdf99
  namespace: govil
spec:
  appName: govil-poc2-consumer-d3fdf99
  depOwner: poc12
  image: docker.io/dimssss/poc2-consumer:d3fdf99-2
  namespace: govil
  profile: dev
  size: "1"
