apiVersion: gov.il/v1alpha1
kind: CoreApiTest
metadata:
  name: govil-coreapitest-9ca9818
  labels:
    profile: dev
spec:
  size: 1
  appName: govil-coreapitest-9ca9818
  image: "docker.io/dimssss/coreapitest:9ca9818-1"
  containerPort: 8080
  profile: dev
  namespace: govil
  latestRouteHost: coreapitest-lab-latest.router.default.svc.cluster.local
  latestRouteName: coreapitest-latest-lab
  resources:
    mongo:
      dbhost: mongo-govil-coreapitest-9ca9818
      dbuser: app
      dbpass: app
      dbname: coreapitestdb
      dbimage: "docker-registry.default.svc:5000/openshift/mongodb:3.6"
  deploymentStrategy:
    type: gb
    weight: 50
