apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: coreapitests.gov.il
spec:
  group: gov.il
  names:
    kind: CoreApiTest
    listKind: CoreApiTestList
    plural: coreapitests
    singular: coreapitest
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
