apiVersion: gov.il/v1alpha1
kind: ReactSample
metadata:
  name: govil-reactsample-f8e9eda
spec:
  size: 1
  appName: govil-reactsample-f8e9eda
  routeName: reactsample-dev
  image: "docker.io/dimssss/react-sample:f8e9eda-1"
  containerPort: 8080
  profile: dev
  namespace: govil
  deploymentStrategy:
    type: gb
    weight: 50
