apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: poc12deps.gov.il
spec:
  group: gov.il
  names:
    kind: Poc12Dep
    listKind: Poc12DepList
    plural: poc12deps
    singular: poc12dep
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
