kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: govil-operator
subjects:
- kind: ServiceAccount
  name: govil-operator
  namespace: govil
roleRef:
  kind: ClusterRole
  name: govil-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-user-govil-operator
subjects:
- kind: User
  name: admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: govil-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-access-operator
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: govil
roleRef:
  kind: ClusterRole
  name: govil-operator
  apiGroup: rbac.authorization.k8s.io
