kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: govil-operator
subjects:
- kind: ServiceAccount
  name: govil-operator
  namespace: govil
roleRef:
  kind: ClusterRole
  name: govil-operator
  apiGroup: rbac.authorization.k8s.io
