kind: Service
apiVersion: v1
metadata:
  name: "{{app_name}}"
  namespace: "{{namespace}}"
spec:
  selector:
    app: "{{app_name}}"
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: {{container_port}}
