apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{service}}'
  namespace: "{{namespace}}"
  labels:
    depOwner: "{{dep_owner}}"
    profile: "{{profile}}"
data:
  PROFILE: prod
  RABBITMQ_IP: "{{service}}"
  RABBITMQ_QUEUE: "{{queue_name}}"
