
# Application objects
- name: Create CoreApiTest Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/app/service.yml') }}"

- name: Create CoreApiTest Route
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/app/route.yml') }}"

- name: Create CoreApiTest Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/app/deployment.yml') }}"
