apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{dbhost}}"
  namespace: "{{namespace}}"
  labels:
    profile: lab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
