apiVersion: v1
kind: Service
metadata:
  name: "{{dbhost}}"
  namespace: "{{namespace}}"
  labels:
    profile: lab
spec:
  ports:
  - name: mongo
    nodePort: 0
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: "{{dbhost}}"
  sessionAffinity: None
  type: ClusterIP
