# Mongodb for DEV
- name: MongoDB Ehpemeral for DEV
  block:
    - name: Create Ehpemeral MongoDB Secret
      k8s:
        state: present
        definition: "{{ lookup('template', 'templates/mongodb/ephemeral/secret.yml') }}"

    - name: Create Ehpemeral MongoDB Service
      k8s:
        state: present
        definition: "{{ lookup('template', 'templates/mongodb/ephemeral/service.yml') }}"

    - name: Create Ehpemeral MongoDB DC
      k8s:
        state: present
        definition: "{{ lookup('template', 'templates/mongodb/ephemeral/dc.yml') }}"
  when: profile == "dev"

# Mongodb for LAB
- name: MongoDB Persistent for LAB
  block:
    - name: MongoDB LAB instance
      debug:
        msg: "{{mongodb_lab}}"

    - name: Create MongoDB Lab Sercet
      k8s:
        state: present
        definition: "{{ lookup('template', 'templates/mongodb/persistent/secret.yml') }}"

    - name: Create MongoDB Lab Service
      k8s:
        state: present
        definition: "{{ lookup('template', 'templates/mongodb/persistent/service.yml') }}"

    - name: Create MongoDB Lab PVC
      k8s:
        state: present
        definition: "{{ lookup('template', 'templates/mongodb/persistent/pvc.yml') }}"

    - name: Create MongoDB Lab DC
      k8s:
        state: present
        definition: "{{ lookup('template', 'templates/mongodb/persistent/dc.yml') }}"

    - name: Wait for MongoDB become up
      k8s_facts:
        kind: DeploymentConfig
        api_version: apps.openshift.io/v1
        namespace: "{{namespace}}"
        name: "{{dbhost}}"
      register: mongodb_dc
      until: 'mongodb_dc.resources | length > 0 and "availableReplicas" in mongodb_dc.resources[0].status and mongodb_dc.resources[0].status.availableReplicas == 1'
      delay: 1
      retries: 60
  when:
    - profile == "lab"
