apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{app_name}}"
  namespace: "{{namespace}}"
spec:
  host: "{{route_prefix}}.{{route_suffix}}"
  to:
    kind: Service
    name: "{{app_name}}"
