kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "{{app_name}}"
  name: "{{app_name}}"
  namespace: "{{namespace}}"
spec:
  replicas: "{{size}}"
  selector:
    matchLabels:
      app: "{{app_name}}"
  template:
    metadata:
      labels:
        app: "{{app_name}}"
    spec:
      containers:
      - name: "{{app_name}}"
        image: "{{image}}"
        ports:
          - containerPort: {{container_port}}
